Sambruk/EgilSCIM

src/data_server.cpp, src/ldap_wrapper.cpp, src/ldap_wrapper.hpp, src/simplescim_ldap.cpp
Makes the LDAP wrapper more cohesive and prepares for alternative implementations (mock or something not based on OpenLDAP)
=> Extracts EGIL related code from the LDAP wrapper

CHANGELOG.md, doc/TROUBLESHOOTING.md, src/simplescim_scim_send.cpp, src/simplescim_scim_send.hpp
=> Option for logging all HTTP traffic to/from the client (#7)

CHANGELOG.md, CMakeLists.txt, doc/USAGE.md, master_config/master.conf, src/cache_file.cpp, src/data_server.cpp, src/data_server.hpp, src/main.cpp, src/scim.cpp, src/scim.hpp, src/simplescim_scim_send.cpp, src/simplescim_scim_send.hpp, src/tests/scim_query_tests.cpp, test/configs/base/master.conf, test/scenarios/base/add_student/description.txt, test/scenarios/base/add_student/grgr.ldif, test/test_server_go/EGILTestServer/main.go
=> The --rebuild-cache functionality

CHANGELOG.md, doc/TROUBLESHOOTING.md, src/generated_load.cpp
=> Adds information about Activity and Employment objects to load log

CHANGELOG.md, src/scim.cpp, src/simplescim_scim_send.cpp, src/simplescim_scim_send.hpp, test/test_server_go/EGILTestServer/main.go, test/tests/add_student/create.txt, test/tests/add_student/spec.json, test/tests/add_student_409/spec.json, test/tests/add_student_409/update.txt, test/tests/add_student_internal_error/spec.json
=> Better treatment of code 409 when a CREATE fails

CHANGELOG.md, doc/TROUBLESHOOTING.md, src/main.cpp, src/model/object_list.hpp
=> Adds command line arguments for forcing an update/create.

CHANGELOG.md, CMakeLists.txt, doc/JSON-REPLACEMENT-RULES.md, src/scim_json_parse.cpp, src/tests/scim_json_parse_tests.cpp
=> Adds regex matching in the switch construct.

CHANGELOG.md, doc/TROUBLESHOOTING.md, src/data_server.cpp, src/simplescim_scim_send.cpp, src/utility/utils.cpp, src/utility/utils.hpp
=> Adds support for date and time format specifiers in log file names.

CHANGELOG.md, master_config/master.conf, src/ldap_wrapper.cpp, test/configs/base/master.conf, test/configs/csv/master.conf, test/configs/dnp/master.conf
=> Optional support for paged LDAP queries

CHANGELOG.md, src/simplescim_scim_send.cpp
=> It is now possible to send a static auth key as an HTTP header.

test/scripts/run_test_suite, test/test_server_go/EGILTestServer/main.go
Now the test suite exits with a failure if any test fails, after all the tests
are ran.
=> Exit with failure if any tests fails

CHANGELOG.md, src/generated_load.cpp
=> Better warning message when school units are missing.

CHANGELOG.md, src/renderer.cpp
=> JSON template rendering errors are now presented better.

CHANGELOG.md, src/generated_load.cpp
=> Improved error message in Activity generation.

CHANGELOG.md, src/fedtlsauth/metadata_parser.cpp
=> Entity IDs are no longer normalized before comparison.

CHANGELOG.md, master_config/Employment.conf, master_config/Student.conf, master_config/StudentGroup.conf, master_config/Teacher.conf, master_config/master.conf, src/data_server.cpp, src/generated_group_load.cpp, src/load_common.cpp, src/load_common.hpp, test/configs/base/Employment.conf, test/configs/base/Student.conf, test/configs/base/StudentGroup.conf, test/configs/base/Teacher.conf, test/configs/base/master.conf, test/configs/csv/master.conf, test/configs/dnp/master.conf, test/configs/virtual_groups/Student.conf, test/configs/virtual_groups/master.conf, test/tests/virtual_groups_limiting/init.txt
=> Orphan filtering fixed and better standard examples.

CHANGELOG.md, src/main.cpp, test/tests/unprovision/delete.txt, test/tests/unprovision/spec.json
=> Command line option for unprovisioning all data

CHANGELOG.md, src/scim.cpp, src/simplescim_scim_send.cpp
=> Improved error message when DELETE fails with 404

CHANGELOG.md, src/scim.cpp, src/utility/utils.cpp, src/utility/utils.hpp
=> Avoid double / when building SCIM URLs

CHANGELOG.md, src/generated_load.cpp
=> Configurable warning for missing generate key for Employment.

CHANGELOG.md, src/scim.cpp
=> Adds a missing use of readable-id.

CHANGELOG.md, doc/USAGE.md, src/model/base_object.hpp, src/tests/transformer_tests.cpp, src/transformer.cpp, src/transformer_impl.cpp, src/transformer_impl.hpp
=> New transform function for URL decoding.

CHANGELOG.md, src/generated_group_load.cpp
=> Transforms can now also be applied for generated (virtual) groups

CHANGELOG.md, src/csv_load.cpp, src/sql_load.cpp
=> Fixed an access violation which could occur when loading from SQL or CSV auxilliary tables.

CHANGELOG.md, doc/TROUBLESHOOTING.md, src/generated_group_load.cpp, src/load_common.cpp, src/load_common.hpp
=> The load log file can now be configured to include relations.
